### ISSUE TITLE
Error in Cloning VM

### ISSUE THREAD

**Issue by docodeid** [emmaliaocode/vagrant-vmware-macos-arm#1]
Hi, was clone this repo, but when I run command "vagrant up" I got error like this : 
<img width="1772" alt="Screenshot 2023-09-29 at 17 16 10" src="https://github.com/emmaliaocode/vagrant-vmware-arm/assets/122348336/7a8844bd-ea86-489c-bcd7-bb8e8af004fb">
Please help

I'm using : 
Vagrant : 2.4.3
VMware Fusion Player Version 13.0.2 (21581413)

**Comment by daoudzd** [comment]
sudo chmod -R a+rwx /Users/xxx/.vagrant.d

**Comment by emmaliaocode** [comment]
@docodeid Since the VM box [starboard/ubuntu](https://app.vagrantup.com/starboard/boxes/ubuntu-arm64-20.04.5) has no further updates after Nov 2022, I've changed the VM box to [bento/ubuntu](https://app.vagrantup.com/bento/boxes/ubuntu-20.04-arm64). Please replace the setting of `config.vm.box` from `starboard/ubuntu-arm64-20.04.5` to `"bento/ubuntu-20.04-arm64"` in your Vagrant file and try it again.
